services:
  fidelio:
    container_name: fidelio-home
    image: ggsheet/fidelio-home:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports: 
      - "8080:8080"